### ISSUE TITLE
VCO Module

### ISSUE THREAD

**Issue by blackearth2014** [lindenbergresearch/LRTRack#10]
Do you have an ETA as to when your VCO will be available for release.

Thanks,

Omar

**Comment by lindenbergresearch** [comment]
Hi Omar,

I got hooked with the filter design und changed some important internal things in sources, so it's delayed a bit and a beta will be available next week. I hope I also can release the filter starting next week.

Cheers, Patrick

**Comment by blackearth2014** [comment]
Your filters alone is worth the wait for your VCO. I am a proud country boy from the deep south here in the U.S. and when I say that your current filter sounds like you put buttermilk in it, please take it as a honorable compliment.

**Comment by lindenbergresearch** [comment]
Thank you! I take it as one :) Sorry for the delay of the modules, had to fight against some problems and errors in math and I am rather a perfectionist ;) 
BTW.: I also grew up in the countryside, so I understand the buttermilk thing :D

**Comment by blackearth2014** [comment]
Are you trying to implement a sweepable slope between 12db-24db lowpass for your filter or was I just dreaming up a concept?

**Comment by blackearth2014** [comment]
Since we are on the subject of Filters and you say that you're perfectionist. Tell me if this is possible from the attached image. I hear this in my head but only known it through hardware chaining. Can you create a 3 peaks filter were as you add your ReShaper Wavefolder to activate when the user cross peaks of each other by a small number of DB's? The white triangles represents the peaks crossover bands for reshape wavefolding.

I hope I made myself clear.

![3 peaks wfold](https://user-images.githubusercontent.com/7956901/34222955-76fe001c-e58b-11e7-84ab-01e7a05cfd4b.png)

**Comment by lindenbergresearch** [comment]
Puh, sounds nice and I surly will do some research in this issue, but for now I just want to have a stable filter released and I am currently fighting against aliasing and interferences at very high resonance and cutoff freq... It is the last problem left, then I will make a new release before Christmas and than the VCO will follow. The great idea here, I will compete later on :) Thanks so far and greetings to ... where are you currently? NY? Cheers, Patrick.

**Comment by blackearth2014** [comment]
I am currently in Amherst, NY. A suburb of Buffalo, NY. Cool Breeze!!

**Comment by lindenbergresearch** [comment]
Implemented in ALMA
