### ISSUE TITLE
build fail, latest source

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#11]
Linux Fedora 23
Rack 0.5.1 from source

Build of your plugin fails here:

g++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/VCO.cpp.o src/VCO.cpp
In file included from src/LindenbergResearch.hpp:6:0,
                 from src/VCO.cpp:3:
src/SimpleFilter.hpp:7:0: warning: "MODULE_WIDTH" redefined
 #define MODULE_WIDTH 12.f
 ^
In file included from src/VCO.cpp:2:0:
src/VCO.hpp:7:0: note: this is the location of the previous definition
 #define MODULE_WIDTH 11.f
 ^
In file included from src/dsp/Oscillator.hpp:3:0,
                 from src/VCO.cpp:1:
src/dsp/DSPMath.hpp:114:43: error: no matching function for call to ‘LP6DBFilter::LP6DBFilter(int)’
     LP6DBFilter filter = LP6DBFilter(18000);
                                           ^
src/dsp/DSPMath.hpp:66:5: note: candidate: LP6DBFilter::LP6DBFilter(sfloat, int)
     LP6DBFilter(sfloat fc, int factor) {
     ^
src/dsp/DSPMath.hpp:66:5: note:   candidate expects 2 arguments, 1 provided
src/dsp/DSPMath.hpp:51:8: note: candidate: constexpr LP6DBFilter::LP6DBFilter(const LP6DBFilter&)
 struct LP6DBFilter {
        ^
src/dsp/DSPMath.hpp:51:8: note:   no known conversion for argument 1 from ‘int’ to ‘const LP6DBFilter&’
src/dsp/DSPMath.hpp:51:8: note: candidate: constexpr LP6DBFilter::LP6DBFilter(LP6DBFilter&&)
src/dsp/DSPMath.hpp:51:8: note:   no known conversion for argument 1 from ‘int’ to ‘LP6DBFilter&&’
In file included from src/VCO.cpp:1:0:
src/dsp/Oscillator.hpp:45:40: error: no matching function for call to ‘LP6DBFilter::LP6DBFilter(int)’
     LP6DBFilter lp1 = LP6DBFilter(20000);
                                        ^
In file included from src/dsp/Oscillator.hpp:3:0,
                 from src/VCO.cpp:1:
src/dsp/DSPMath.hpp:66:5: note: candidate: LP6DBFilter::LP6DBFilter(sfloat, int)
     LP6DBFilter(sfloat fc, int factor) {
     ^
src/dsp/DSPMath.hpp:66:5: note:   candidate expects 2 arguments, 1 provided
src/dsp/DSPMath.hpp:51:8: note: candidate: constexpr LP6DBFilter::LP6DBFilter(const LP6DBFilter&)
 struct LP6DBFilter {
        ^
src/dsp/DSPMath.hpp:51:8: note:   no known conversion for argument 1 from ‘int’ to ‘const LP6DBFilter&’
src/dsp/DSPMath.hpp:51:8: note: candidate: constexpr LP6DBFilter::LP6DBFilter(LP6DBFilter&&)
src/dsp/DSPMath.hpp:51:8: note:   no known conversion for argument 1 from ‘int’ to ‘LP6DBFilter&&’
../../compile.mk:53: recipe for target 'build/src/VCO.cpp.o' failed
make: *** [build/src/VCO.cpp.o] Error 1

Any suggestions ?

**Comment by lindenbergresearch** [comment]
Hi Dave,

I just pushed today all collected commits to have it save, but the current state of the code is a mess. I'm still on research and development, compile errors may be. If I have a stabile beta I will tell you :) 
However you can check new commits and look if it compiles if you want.

Cheers, Patrick.

**Comment by davephillips** [comment]
Hey Patrick,

Latest commit builds cleanly now, all modules display properly except the VCO. See attached image, the small knobs are displaced a bit.

![lrt-vco-small-knobs-off](https://user-images.githubusercontent.com/7815938/34358292-8c6e448a-ea1c-11e7-8775-d5bff5b34eb9.png)

**Comment by lindenbergresearch** [comment]
It is just the latest state of development, VCO so far is untouched und unfinished, I decided to complete the filter at first. I tell you, when I'll have a release-able state, then sources get tagged with 0.0.4 :) Thanks so far for help! Cheers

**Comment by lindenbergresearch** [comment]
Hi Dave,

I will be ready with  a new version around today evening (German Time). It would be very nice, if you could compile and test it for windows :) 
I excluded the VCO for now until it will be stable for release.

I'm looking forward to hear your feedback on the new filter :D 

Patrick
