### ISSUE TITLE
Alma Filter

### ISSUE THREAD

**Issue by blackearth2014** [lindenbergresearch/LRTRack#13]
Your grandmother would be proud. The Alma Filter is all buttermilk, Brah.

**Comment by lindenbergresearch** [comment]
Thanks a lot! Nice to hear - I spend a lot of time creating it...
The VCO module will follow this or next week.

**Comment by blackearth2014** [comment]
Please tell me that it is a new concept and design. Some recent VCO modules are a folk from the Fundamental VCO modules. I personally feel that feel is good for very basic sound generation, but fall week of character and personality. Please give it some byte so that your filter can grab some harmonics and give us that buttermilk sweeps.

**Comment by lindenbergresearch** [comment]
Basically it is a standard VCO based on BLIT technology with a integrated waveshaper, producing saw, pulse, sine and tri... I am currently brainstorming what could be added to get some special things... any ideas? 

cheers
the buttermilk guy ;)

**Comment by blackearth2014** [comment]
How about adding a special noise output via a switch that the types can be changed with the Frequency and Resonance knobs. Also too add a LED display above the Frequency knob so that you can easily dial in the pitch. I want to use drum pulse triggers on VCOs chords. I know that there are modules that does this, but they are not that intuitive when you first look at them.

Thanks

**Comment by MarcBoule** [comment]
Just wanted to squeeze in here for one post and echo the first post above: your Alma filter is very awesome! When filtering a saw wave from the E340 and playing around with resonance, drive and slope, I was able to get some **really** cool sounds out of it! Thanks for the filter, and those extra controls are most welcome 👍

**Comment by phdsg** [comment]
very nice sound indeed. good work.
one small thing tho: cv over slope? pretty please. :)

**Comment by lindenbergresearch** [comment]
Thank you guys! :D  
I am very happy to read good critics!

I spend really a lot of time creating modules like Alma. Well including graphics and math-research I went up to around 100 hours I guess... ;P 
So I am very glad people like und use it to make sounds and music. :) 

@phdsg 
I already have CV => SLOPE on my TODO for further updates and improvements ;)  

Have a nice WE,
Patrick
