### ISSUE TITLE
LRTRack v0.5.185: inappropriate tags

### ISSUE THREAD

**Issue by DomiKamu** [lindenbergresearch/LRTRack#14]
Hi,

I report tags issues for some modules:
- Blank Panel 12TE / 20TE would be "Blank" (instead of "Utility").
- ReShaper Wavefolder would be "Waveshaper" (instead of "Filter/VCF"). GUI indicates "VCS Waveshaper" when the module is loaded in rack.

Regards.

**Comment by lindenbergresearch** [comment]
Hi,

thanks for the info :D 
Will be fixed in the next release... ;) 

Patrick

**Comment by lindenbergresearch** [comment]
Fixed.
