### ISSUE TITLE
LRTRack 0.5.210: can't compile on Windows platform

### ISSUE THREAD

**Issue by DomiKamu** [lindenbergresearch/LRTRack#15]
Platform: Windows 7 Pro SP1 (x64)
VCV Rack **dev** (based on 0.5.1), on C:\Rack
LRTRack v0.5.210

Hi, I don't understand why I can't compile Windows binaries (having the same problem with previous 0.5.185)? what's I'm wrong? thanks in advance (sorry some messages are displayed in French in this log, because my Windows 7 Pro SP1 x64 is **French-localized**).

DoM@HAL-9000 MINGW64 /C/Rack/plugins/LRTRack
$ make
Makefile:28: avertissement : surchargement de la recette pour la cible « dist »
../../plugin.mk:36: avertissement : ancienne recette ignorée pour la cible « dist »
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.185 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/AlmaFilter.cpp.o src/AlmaFilter.cpp
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.185 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/SimpleFilter.cpp.o src/SimpleFilter.cpp
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.185 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/BlankPanel.cpp.o src/BlankPanel.cpp
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.185 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/ReShaper.cpp.o src/ReShaper.cpp
src/ReShaper.cpp: In member function 'virtual void ReShaper::step()':
src/ReShaper.cpp:38:27: error: call of overloaded 'abs(float&)' is ambiguous
     float out = x * (abs(x) + a) / (x * x + (a - 1) * abs(x) + 1);
                           ^
In file included from C:/msys64/mingw64/include/c++/6.2.0/cstdlib:75:0,
                 from C:/msys64/mingw64/include/c++/6.2.0/stdlib.h:36,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/LindenbergResearch.hpp:3,
                 from src/ReShaper.cpp:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:338:15: note: candidate: int abs(int)
   int __cdecl abs(int _X);
               ^~~
In file included from C:/msys64/mingw64/include/c++/6.2.0/stdlib.h:36:0,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/LindenbergResearch.hpp:3,
                 from src/ReShaper.cpp:1:
C:/msys64/mingw64/include/c++/6.2.0/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
C:/msys64/mingw64/include/c++/6.2.0/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
src/ReShaper.cpp:38:60: error: call of overloaded 'abs(float&)' is ambiguous
     float out = x * (abs(x) + a) / (x * x + (a - 1) * abs(x) + 1);
                                                            ^
In file included from C:/msys64/mingw64/include/c++/6.2.0/cstdlib:75:0,
                 from C:/msys64/mingw64/include/c++/6.2.0/stdlib.h:36,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/LindenbergResearch.hpp:3,
                 from src/ReShaper.cpp:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdlib.h:338:15: note: candidate: int abs(int)
   int __cdecl abs(int _X);
               ^~~
In file included from C:/msys64/mingw64/include/c++/6.2.0/stdlib.h:36:0,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/LindenbergResearch.hpp:3,
                 from src/ReShaper.cpp:1:
C:/msys64/mingw64/include/c++/6.2.0/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^~~
C:/msys64/mingw64/include/c++/6.2.0/cstdlib:172:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^~~
make: *** [../../compile.mk:54: build/src/ReShaper.cpp.o] Error 1

**Comment by DomiKamu** [comment]
Adding some informations, may be help about method I'm using (perhaps I'm wrong somewhere):

- Starting from compiled VCV Rack (located into C:\Rack) as explained into VCV Rack compile tutorial. No permission issue on C: and subdires, no firewall issue, using **MSYS2 MinGW 64-bit**.

Sequence of commands I've typed:

**cd /C/Rack/plugins**
**git clone https://github.com/lindenbergresearch/LRTRack.git**
**cd LRTRack**
**git submodule update --init --recursive** _(same issue if I don't use this "git" command)_
**make**

Help will be appreciated, thanks a lot in advance.

Dominique.

**Comment by lindenbergresearch** [comment]
I will change all 'abs()' to 'fabs()' so it should be not problem to compile it for win in the next releases.
