### ISSUE TITLE
windows version 0.5.210

### ISSUE THREAD

**Issue by Phal-anx** [lindenbergresearch/LRTRack#16]
[LindenbergResearch-0.5.185-win.zip](https://github.com/lindenbergresearch/LRTRack/files/1661733/LindenbergResearch-0.5.185-win.zip)

**Comment by Phal-anx** [comment]
as you can see on the version number of the zip file it shows 0.5.185 instead of 0.5.210 which is what i downloaded... the version number in the makefile needs to be fixed ...

**Comment by lindenbergresearch** [comment]
I just forgot to pull the adapted Makefile with the new version. Did it now ... :)
