### ISSUE TITLE
VCO release

### ISSUE THREAD

**Issue by blackearth2014** [lindenbergresearch/LRTRack#20]
I see a VCO svg file in the res folder. When will you think that you will be able to release it. The graphics looks nice. The parameters seems like there is something all new going on with the standard 4 waveforms.

**Comment by lindenbergresearch** [comment]
Well, actually it is just a standard VCO currently, but based on modern analog-modeling technics which sound warm and without that digital "plastic" aliasing. I just added some neat features like have an extra channel where you can mix all waves to an output. I added a waveshaper, but it results in no musical useful sound, so some kind of extra-feature is currently missing to complete it... I am thinking about ;) 
The next release will be a virtual-analoge modelling version of the famous MS20 filter, based on modern circuit modelling technics, maybe it's ready next week.

**Comment by blackearth2014** [comment]
THE MS20 filter is butter. Take your time on this one and enjoy yourself doing it.
