### ISSUE TITLE
Versioning on the blankpanel

### ISSUE THREAD

**Issue by Phal-anx** [lindenbergresearch/LRTRack#21]
Hi! 

I asked you today if it is ok to "steal" the part of the code which lets you show the versioning on the blankpanel.. after I was finished and got it working "properly" I noticed that when I use zoom in Rack that it wont behave like I thought it would. Meaning that I will not get bigger or smaller the same way everything else does. Best would be if you try it yourself to see what I mean. It also happens to your blankpanel ;)

**Comment by lindenbergresearch** [comment]
Hey :)

Hm, I am not sure what you mean. Scaling seems to be OK here. Do you used the complete code including my simple LCD display component and the corresponding truetype?
The quality of the font scaling is, well, not the best... but it's ok for me.

Cheers,
Patrick

p.s. Wir können auch gerne Deutsch reden, wenn du magst ;)

**Comment by Phal-anx** [comment]
haahaa.. Ist mir gar nicht aufgefallen, das du deutsch sprichst. 

Also wenn ich in Rack Zoom verwende, ist die Vergrößerung der Schrift nicht gleichgesetzt mit der Vergrößerung des Moduls. Es ist jetzt wirklich nicht weltbewegend aber immerhin soviel das es auffällt wenn man reinzoomt. Den Code hab ich komplett übernommen und dann halt an meine Wünsche angepasst (Farbe, Größe, Fonts-Style). 
Ich dachte mir, solltest du "Zoom" nicht getestet haben, wärs gut wenn du davon weißt.

**Comment by lindenbergresearch** [comment]
Also ich hab das jetzt noch mal getestet und bei mir ist alles ordentlich proportional :-/ Also ich habe nicht nachgemessen, aber es schaut immer gleich aus... kannst du mir mal 2 Bilder schicken als Vergleich? Strange...
Danke auf jeden Fall für die Info! :)

**Comment by Phal-anx** [comment]
![1](https://user-images.githubusercontent.com/31989694/35436549-266f939c-028f-11e8-9b23-0ba6dbccb2e9.png)
![2](https://user-images.githubusercontent.com/31989694/35436550-268d71d2-028f-11e8-919b-1e5a850b13d8.png)

die Anfangspostion von "VERSION 0.5.210" bleibt gleich aber das Ende verschiebt sich ein Stück. Wie gesagt nicht weltbewegt aber doch sichtbar.

**Comment by Phal-anx** [comment]
proportional ist das natürlich ok! Da es sonst die Schrift in die Länge ziehen würde, was ja auch nicht gut aussehen würde.

**Comment by lindenbergresearch** [comment]
Ach tatsächlich, ist mir gar nicht aufgefallen - ich hatte nur die Höhe betrachtet... Ich denke mal, das hängt mit den Zeichenabständen der Renderengine zusammen. Wenn man die Version via Illustrator statisch im SVG ablegt, dann sollte es gehen, würde ich aber nicht machen.
Naja, so lange es halbwegs gut ausschaut ;) Aber danke für den Hinweis :D

**Comment by lindenbergresearch** [comment]
Ich schliesse mal das Thema. für mich kein Problem, aber danke noch mal für den Hinweis
