### ISSUE TITLE
build fail with GCC 5.3.1

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#22]
Fedora 23 Linux
Rack 0.5.x

I can solve some C++ issues but not this one:

g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.210 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/MS20Filter.cpp.o src/MS20Filter.cpp
In file included from src/dsp/MS20zdf.hpp:4:0,
                 from src/MS20Filter.cpp:1:
src/dsp/DSPSystem.hpp:38:9: error: ‘virtual’ can only be specified for functions
         };
         ^
src/dsp/DSPSystem.hpp:44:9: error: ‘virtual’ can only be specified for functions
         };
         ^
src/dsp/DSPSystem.hpp:50:9: error: ‘virtual’ can only be specified for functions
         };
         ^
../../compile.mk:53: recipe for target 'build/src/MS20Filter.cpp.o' failed
make: *** [build/src/MS20Filter.cpp.o] Error 1

**Comment by davephillips** [comment]
NB: I resolved the issue for the moment by removing the virtual specifier. Everything compiles now, but I have no idea if my changes will affect performance. Please advise if there's a better fix, thanks.

**Comment by lindenbergresearch** [comment]
Hi Dave,

nevermind - all under construction - I am experimenting with an DSP abstraction layer... I will use a developer branch soon instead of the master to avoid such troubles ;) 
Dropping the 'virtual' is absolutely correct :) 

Thanks for reporting.

Patrick
