### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#24]
Fedora 23 Linux
Rack 0.5.x

g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.210 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/MS20Filter.cpp.o src/MS20Filter.cpp
src/MS20Filter.cpp: In member function ‘virtual void MS20Filter::step()’:
src/MS20Filter.cpp:76:14: error: ‘struct dsp::MS20zdf’ has no member named ‘setType’
     ms20zdf->setType(params[MODE_SWITCH_PARAM].value);
              ^
../../compile.mk:53: recipe for target 'build/src/MS20Filter.cpp.o' failed
make: *** [build/src/MS20Filter.cpp.o] Error 1

**Comment by lindenbergresearch** [comment]
try again, should work now. 
current version 0.5.289 is a beta version ready for testing if you want :) 
this would be very welcome, if you like.

**Comment by davephillips** [comment]
Hey, thanks for the notice, sorry for the late reply. Build is fixed, I'll test the version this evening after teaching.

**Comment by lindenbergresearch** [comment]
You are welcome! May you send me a linux dist? I already have win and mac for v0.5.3. This would be very nice, so I could release today :)

**Comment by davephillips** [comment]
First time doing a dist, I hope I did it right. Btw, I had to change LICENCE to LICENSE before it would build. :)
[LindenbergResearch-0.5.3-lin.zip](https://github.com/lindenbergresearch/LRTRack/files/1710648/LindenbergResearch-0.5.3-lin.zip)

**Comment by lindenbergresearch** [comment]
Oh yes, you are right... I will fix this soon :) Thanks a lot for compiling!
