### ISSUE TITLE
Valerie output bug: inf and nan

### ISSUE THREAD

**Issue by MarcBoule** [lindenbergresearch/LRTRack#25]
Hi Patrick,

I've been having an intermittent bug with the Valerie filter, and so far I'm not sure how exactly to reproduce it. I'm posting the issue anyways, in case others have observed this, and more data can be gathered to help debug. The problem is that sometimes the output gets stuck at "inf" and no sound comes out. When I close Rack and restart it, the problem goes away.

![image](https://user-images.githubusercontent.com/33604154/36237595-ab592344-11ca-11e8-9730-15475a9c0d8d.png)

I'm using Rack 0.5.1, and version 0.5.3 of the LRTRack plugins, on windows 10. 

As a side note, when I tried the Valerie filter on my macbook air, I actually got a "nan" in the output at one point, but once again, when I closed Rack and started it up again, all was normal and I couldn't repeat the bug. Sorry if this is not super helpful.

**Comment by lindenbergresearch** [comment]
Hi Marc,

thanks a lot for the report. It seems very strange, because I can't replicate it... what samplerate did you use?

Cheers,
Patrick

**Comment by MarcBoule** [comment]
44,1 kHz. I figured my report would not be very useful, since I myself can't replicate it regularly, but when I saw that it happened a couple of times, and on both Win and Mac, and that I never saw the bug with any other filter I have used in Rack, then I figured I might report it. Hopefully someone else will chime in, and if I find anything more concrete, I'll report back here also. Thanks!

**Comment by lindenbergresearch** [comment]
I was finally able to reproduce the bug and I fixed it today. I did some stress-tests and now everything seems to run stable. The fix will be implemented in the 0.6.0 release, which will be published when Rack 0.6.xx is released. Thanks again for reporting. The current master already have the bugfix.

**Comment by MarcBoule** [comment]
Wow, thanks so much Patrick, glad to know that you were able to get something out of my report ;-) Best regards!

**Comment by lindenbergresearch** [comment]
You are welcome :)
