### ISSUE TITLE
Master updated to 0.6.xx

### ISSUE THREAD

**Issue by lindenbergresearch** [lindenbergresearch/LRTRack#27]
The last two day's I migrated the current sources to work with the upcoming v0.6.xx of Rack. For detailed information on what has been changed please see the API update thread at the Rack issue discussions. 
You will have to fetch the current 0.6.xxdev in order to get the plugin running fine. I suggest to do a clean build - I had some trouble while updating the current 0.5.xx repo and started from scratch - then it worked fine.
If you encounter any issue with the migration, please post it here. For now it seems to run fine on my machine.

Cheers,
Patrick

**Comment by Coirt** [comment]
Bravo Patrick look fantastic and sounding great too!

**Comment by lindenbergresearch** [comment]
Thanks a lot :)

**Comment by zezic** [comment]
Hi. For me Oscillator UI looks strange. Both Rack and LRTRack modules built from latest master. I'm on Linux box.
![is_osc_ui_broken](https://user-images.githubusercontent.com/1945127/37870072-cc8f8eda-2fd5-11e8-8b1a-30d9159d4bed.png)

**Comment by lindenbergresearch** [comment]
It's ok so far. You are on the master branch, which means that it is always "under construction" it is just the current state of development. I still working on the oscillator and it is not finished yet... as you can see, the UI has to be finished and also the functions inside.
