### ISSUE TITLE
build fail: setShape

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#28]
Linux Fedora 23
Rack master (0.6.x dev)

g++ -Wsuggest-override -std=c++11 -fPIC -I../../include -I../../dep/include -DSLUG=LindenbergResearch -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCO.cpp.o src/VCO.cpp
src/VCO.cpp: In member function ‘virtual void VCO::step()’:
src/VCO.cpp:55:14: error: ‘struct dsp::BLITOscillator’ has no member named ‘setShape’
         osc->setShape(shape);
              ^
../../compile.mk:57: recipe for target 'build/src/VCO.cpp.o' failed
make: *** [build/src/VCO.cpp.o] Error 1

Any suggestions for fixing ?

**Comment by lindenbergresearch** [comment]
mea culpa. forgot to commit something... fixed. ;)
