### ISSUE TITLE
FrameBufferWidget error

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#29]
Almost there now:

g++ -Wsuggest-override -std=c++11 -fPIC -I../../include -I../../dep/include -DSLUG=LindenbergResearch -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/LRComponents.cpp.o src/LRComponents.cpp
src/LRComponents.cpp: In constructor ‘SVGRotator::SVGRotator()’:
src/LRComponents.cpp:240:42: error: cannot call constructor ‘SVGRotator::FramebufferWidget’ directly [-fpermissive]
     FramebufferWidget::FramebufferWidget();
                                          ^
src/LRComponents.cpp:240:42: note: for a function-style cast, remove the redundant ‘::FramebufferWidget’
../../compile.mk:57: recipe for target 'build/src/LRComponents.cpp.o' failed
make: *** [build/src/LRComponents.cpp.o] Error 1

Changing the line to simply FrameBufferWidget(); does allow the build to complete.

**Comment by lindenbergresearch** [comment]
Sorry, I grow up in the Java world... hope it is fixed now ...

**Comment by davephillips** [comment]
Yep, all good now, thanks !
