### ISSUE TITLE
Re Woldemar

### ISSUE THREAD

**Issue by cunabula27** [lindenbergresearch/LRTRack#31]
Hi Patrick,

Just a note to ask if Woldemar is still a work in progress?

It's rendering like this in Windows 10 (Rack 0.6):

![2018-03-28 2](https://user-images.githubusercontent.com/24782488/38045993-5448cebc-32b6-11e8-9de5-b77c4640bb47.png)

The representation of CV modulation on the knobs in Valerie is stunning.

All the best,

Adrian

**Comment by lindenbergresearch** [comment]
Hi Adrian,

yes, it is still in progress and accidentally published via the plugin manager :-/ I don't know why. I created a valid version, you can find in the release section :) 

Thanks for reporting and happy eastern!

Patrick

**Comment by rHutter** [comment]
I have the same issue (NO LABELS!!) on Windows 7 and Windows 8.1 (both 64 bit)... Can't understand what those knobs or those input plugs are. Only the 4 wave outputs are correctly labeled.

**Comment by lindenbergresearch** [comment]
Sorry, as I mentioned before, the module has been accidentally released - actually it wasn't ready yet.
I had no time the last weeks to go on in this project, so it stayed this way.
I will continue it the next weeks and you'll get a usable version.

Cheers,
Patrick

**Comment by lindenbergresearch** [comment]
See current implementation
