### ISSUE TITLE
Anybody out there for compiling a linux version for me? :) 

### ISSUE THREAD

**Issue by lindenbergresearch** [lindenbergresearch/LRTRack#32]

**Comment by ZuluEchoRomeOscar** [comment]
[LindenbergResearch-0.6.0-lin.zip](https://github.com/lindenbergresearch/LRTRack/files/1865465/LindenbergResearch-0.6.0-lin.zip)

There you go - and thanks for the beautiful modules!

**Comment by lindenbergresearch** [comment]
Thanks! You are welcome :)
