### ISSUE TITLE
Could your 0.6.0 modules please be compiled?

### ISSUE THREAD

**Issue by vogelscheiss** [lindenbergresearch/LRTRack#33]
I'm unable to go through all the steps involved in compiling the code for these modules for use on my Mac. But I'm a big fan of the -24dB filter, and have a number of patches that use it that won't work anymore.

Would it be asking to much that these modules be distributed in the normal fashion in the VCV Rack plugin manager with versions that are ready for use?

Thanks.

**Comment by lindenbergresearch** [comment]
Hi,

actually it should work fine. I recovered in some old version all historical modules like the VCF 24dB.
Just the color was adapted to fit into the new bluish design. The code is exactely the same, as well as all inputs and the graphics.

What exactly does not work?

Regards,
Patrick

**Comment by vogelscheiss** [comment]
After unzipping LindenbergResearch-0.6.0-mac.zip into my plugins folder and restarting VCV Rack, I get this on starting VCV Rack:

"Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/LindenbergResearch
See log for details."

And I still get this when loading up a patch containing LPFilter24dB:

![image](https://user-images.githubusercontent.com/38222883/38566829-b05198c8-3cb2-11e8-8f26-7ee2a46471d0.png)

So something is clearly going wrong. Any insights?

**Comment by vogelscheiss** [comment]
Please be aware that you have – probably unintentionally – renamed your modules in the 0.6.0 release. This has had the effect of breaking old patches that used your modules. 

You've changed "Lindenberg Research" to "LindenbergResearch".

For now I'll edit the slugs in my .vcv files, but wanted you to know.

![image](https://user-images.githubusercontent.com/38222883/38589769-ff279932-3cfa-11e8-8f8f-73da5a3b5319.png)
