### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by caecos** [lindenbergresearch/LRTRack#34]
$ make
g++ -Wsuggest-override -std=c++11 -DSLUG=LindenbergResearch -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/AlmaFilter.cpp.o src/AlmaFilter.cpp
src/AlmaFilter.cpp: In constructor 'AlmaFilterWidget::AlmaFilterWidget(AlmaFilter*)':
src/AlmaFilter.cpp:141:40: error: 'LRRedLight' was not declared in this scope
     addChild(ModuleLightWidget::create<LRRedLight>(Vec(85, 247), module, AlmaFilter::OVERLOAD_LIGHT));
                                        ^~~~~~~~~~
src/AlmaFilter.cpp:141:40: note: suggested alternative: 'LRLight'
     addChild(ModuleLightWidget::create<LRRedLight>(Vec(85, 247), module, AlmaFilter::OVERLOAD_LIGHT));
                                        ^~~~~~~~~~
                                        LRLight
src/AlmaFilter.cpp:141:100: error: no matching function for call to 'rack::ModuleLightWidget::create<<expression error> >(rack::Vec, AlmaFilter*&, AlmaFilter::LightIds)'
     addChild(ModuleLightWidget::create<LRRedLight>(Vec(85, 247), module, AlmaFilter::OVERLOAD_LIGHT));
                                                                                                    ^
In file included from ../../include/rack.hpp:9:0,
                 from src/dsp/DSPMath.hpp:5,
                 from src/dsp/LadderFilter.hpp:6,
                 from src/AlmaFilter.cpp:1:
../../include/app.hpp:447:12: note: candidate: template<class T> static T* rack::ModuleLightWidget::create(rack::Vec, rack::Module*, int)
  static T *create(Vec pos, Module *module, int firstLightId) {
            ^~~~~~
../../include/app.hpp:447:12: note:   template argument deduction/substitution failed:
src/AlmaFilter.cpp:141:100: error: template argument 1 is invalid
     addChild(ModuleLightWidget::create<LRRedLight>(Vec(85, 247), module, AlmaFilter::OVERLOAD_LIGHT));
                                                                                                    ^
make: *** [../../compile.mk:65: build/src/AlmaFilter.cpp.o] Error 1

**Comment by lindenbergresearch** [comment]
Should be OK now. It is currently in development, stable Versions are Tagged ;)
