### ISSUE TITLE
CV Control "Overextends" Limit of Control of Frequency of Alma Filter

### ISSUE THREAD

**Issue by jonheal** [lindenbergresearch/LRTRack#36]
Scenario:  The CV knob is all the way to the right for Frequency on the Alma, and I am controlling it with a knob on my physical control device via the MIDI-CC device. If the Frequency knob is set fairly far to the right to begin with, before I have made a complete turn of my physical knob, CV control tops out (as expected). What isn't expected (to me, anyway) is that the sound from the filter cuts out for a portion of the turn and then behaves as if the Frequency knob is all the way to the left, as well. Is this by design? This behavior does not occur on the Valerie filter.

**Comment by lindenbergresearch** [comment]
Hm, I think its buggy... I will check it the next days... ;) 
Thanks a lot for reporting!

**Comment by lindenbergresearch** [comment]
Seems to be fixed :)
