### ISSUE TITLE
Westcoast module crashes Rack

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#37]
Fedora 23 Linux
Rack 0.6.x (built from source)

No problems building the plugin, and all other modules load and seem fine. When I try to load the Westcoast module it crashes Rack. Here's the edited output from 'make debug':

...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcd109700 (LWP 2875)]
Westcoast::step (this=0x16a12a0) at src/Westcoast.cpp:72
72	        gain->setIndicatorActive(inputs[CV_GAIN_INPUT].active);
...
(gdb) thread apply all bt 
Thread 5 (Thread 0x7fffcd109700 (LWP 2875)):
#0  0x00007fffe20ec4a3 in Westcoast::step() (this=0x16a12a0) at src/Westcoast.cpp:72
#1  0x000000000051664f in rack::engineRun() () at src/engine.cpp:128
#2  0x000000000051664f in rack::engineRun() () at src/engine.cpp:172
#3  0x00007ffff45eaf20 in  () at /lib64/libstdc++.so.6
#4  0x00007ffff7bc561a in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff3d5a5fd in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fffce023700 (LWP 2874)):
#0  0x00007ffff7bce28d in nanosleep () at /lib64/libpthread.so.0
#1  0x0000000000520448 in rack::serverRun() (__rtime=...) at /usr/include/c++/5.3.1/thread:292
#2  0x0000000000520448 in rack::serverRun() () at src/bridge.cpp:358
#3  0x0000000000520448 in rack::serverRun() () at src/bridge.cpp:371
#4  0x00007ffff45eaf20 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff7bc561a in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff3d5a5fd in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fffce884700 (LWP 2873)):
#0  0x00007ffff3d4eb7d in poll () at /lib64/libc.so.6
#1  0x00007ffff4dec18c in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007ffff4dec512 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#3  0x00007ffff586e516 in gdbus_shared_thread_func () at /lib64/libgio-2.0.so.0
#4  0x00007ffff4e128e5 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007ffff7bc561a in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff3d5a5fd in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffcf085700 (LWP 2872)):
#0  0x00007ffff3d4eb7d in poll () at /lib64/libc.so.6
#1  0x00007ffff4dec18c in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#2  0x00007ffff4dec29c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007ffff4dec2d9 in glib_worker_main () at /lib64/libglib-2.0.so.0
#4  0x00007ffff4e128e5 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#5  0x00007ffff7bc561a in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff3d5a5fd in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f9f9c0 (LWP 2868)):
#0  0x00007ffff3d549e7 in munmap () at /lib64/libc.so.6
#1  0x00007ffff3cd3a52 in __GI__IO_setb () at /lib64/libc.so.6
#2  0x00007ffff3cd1e7e in __GI__IO_file_close_it () at /lib64/libc.so.6
#3  0x00007ffff3cc5aff in fclose@@GLIBC_2.2.5 () at /lib64/libc.so.6
#4  0x0000000000534f2c in nsvgParseFromFile(char const*, char const*, float) (filename=<optimized out>, units=0x7c9083 "px", dpi=75) at dep/include/nanosvg.h:2896
#5  0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (filename="./plugins/LRTRack/res/Westcoast.svg", this=0x16b3f70) at src/window.cpp:692
#6  0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__p=<optimized out>, this=<optimized out>)
    at /usr/include/c++/5.3.1/ext/new_allocator.h:120
#7  0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__p=<optimized out>, __a=...)
    at /usr/include/c++/5.3.1/bits/alloc_traits.h:530
#8  0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__a=..., this=0x16b3f60)
    at /usr/include/c++/5.3.1/bits/shared_ptr_base.h:522
#9  0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__a=..., this=<optimized out>)
    at /usr/include/c++/5.3.1/bits/shared_ptr_base.h:617
#10 0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__a=..., __tag=..., this=<optimized out>)
    at /usr/include/c++/5.3.1/bits/shared_ptr_base.h:1097
#11 0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__a=..., __tag=..., this=<optimized out>)
    at /usr/include/c++/5.3.1/bits/shared_ptr.h:319
#12 0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (__a=...) at /usr/include/c++/5.3.1/bits/shared_ptr.h:620
#13 0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /usr/include/c++/5.3.1/bits/shared_ptr.h:636
#14 0x0000000000537067 in rack::SVG::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (filename="./plugins/LRTRack/res/Westcoast.svg")
    at src/window.cpp:709
#15 0x00007fffe20ef8b2 in WestcoastWidget::WestcoastWidget(Westcoast*) (this=this@entry=0x16a32f0, module=module@entry=0x16a12a0, __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at src/Westcoast.cpp:123
#16 0x00007fffe20f41a2 in rack::Model* rack::Model::create<Westcoast, WestcoastWidget, rack::ModelTag>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, rack::ModelTag)::TModel::createModuleWidget() (this=0xc26c20) at ../../include/plugin.hpp:78
#17 0x000000000055d907 in rack::ModelItem::onAction(rack::EventAction&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:139
#18 0x000000000055dba5 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>) at src/app/ModuleBrowser.cpp:92
#19 0x000000000055dba5 in rack::BrowserListItem::onDragDrop(rack::EventDragDrop&) (this=<optimized out>, e=...) at src/app/ModuleBrowser.cpp:86
#20 0x00000000005373ac in rack::mouseButtonCallback(GLFWwindow*, int, int, int) (window=window@entry=0xff6980, button=0, action=<optimized out>, mods=<optimized out>) at src/window.cpp:117
#21 0x0000000000537be9 in rack::windowRun() () at src/window.cpp:144
#22 0x0000000000537be9 in rack::windowRun() () at src/window.cpp:447
#23 0x00000000004c6e2c in main(int, char**) (argc=<optimized out>, argv=0x7fffffffda98) at src/main.cpp:107
(gdb) 

I hope that helps. Thanks for the great modules !

**Comment by lindenbergresearch** [comment]
Hi Dave,

thanks for the report!
Please check, if the problem still exists...

Cheers,
Patrick

**Comment by davephillips** [comment]
Hey Patrick, the latest pull solves my problem with the Westcoast module. Thank you !

**Comment by lindenbergresearch** [comment]
Yes, I did not know that even pointers have to be initialized in C++. Compared an uninitialized pointer with NULL... I come from Java... this is strange to me ;P 
Thanks again for reporting!
