### ISSUE TITLE
build fail with latest pull

### ISSUE THREAD

**Issue by davephillips** [lindenbergresearch/LRTRack#38]
Fedora 23 Linux
VCV Rack 0.6.2b

g++ -Wsuggest-override -std=c++11 -DSLUG=LindenbergResearch -fPIC -I../../include -I../../dep/include -DVERSION=0.6.2_beta-5 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/dsp/LambertW.cpp.o src/dsp/LambertW.cpp
src/dsp/LambertW.cpp:18:17: error: ‘dsp’ is not a namespace-name
 using namespace dsp;
                 ^
src/dsp/LambertW.cpp:18:20: error: expected namespace-name before ‘;’ token
 using namespace dsp;

More errors follow, I think they all stem from the namespace error. Any suggestions for fixing ?

**Comment by lindenbergresearch** [comment]
I did some reformat and imports cleanup of the sources... seems that it messed up things :-(

**Comment by lindenbergresearch** [comment]
fixed.
