### ISSUE TITLE
VCO is invisible except for 4 screws

### ISSUE THREAD

**Issue by metaphorz** [lindenbergresearch/LRTRack#4]
On the Mac, after building for 0.5.0, I can select each module except for Voltage Controlled Oscillator. When that is selected, an empty module appears in Rack which is apparent only by the black screws. The module itself is not there.

**Comment by phdsg** [comment]
the vco looks like a wip template. probably coming soon.

**Comment by metaphorz** [comment]
Good point on the tagging. A lot of folks do not do this, so I sometimes forget to check, but I agree that this is logical -- the bleeding wip can be untagged

**Comment by lindenbergresearch** [comment]
:)
