### ISSUE TITLE
Laika Classic Dark skin is missing inner pointers on knobs when cv is added/connected

### ISSUE THREAD

**Issue by Petervos2018** [lindenbergresearch/LRTRack#41]
Hi Patrick

I think the subject says enough , the white knobs do not get a black triangle when I connect cv to one of the three knobs freq/res/sat.

Thanks for your great plugins,

Greetings Peter.

**Comment by lindenbergresearch** [comment]
Hi Peter,

sorry I was a bit busy and didn't read it till now...
Thanks a lot for reporting this issue... I will take a look soon, while I am working on a new version.

Cheers,
Patrick

**Comment by Petervos2018** [comment]
Hi Patrick,

No problem, just glad you are still working on your modules (when you find the time).
Take your time , and thanks for answering,

Greets Peter.

**Comment by Petervos2018** [comment]
I saw the new 0.6.5. version is ready to be relaesed, but you did not fix the issue I reported.
The new filter sure looks nice :) 

Greets Peter

**Comment by lindenbergresearch** [comment]
Shame on me... totally forgot it... I will fix it in the next release...

**Comment by lindenbergresearch** [comment]
Fixed in v1 :)
