### ISSUE TITLE
Vampyr drive cv too responsive 

### ISSUE THREAD

**Issue by Petervos2018** [lindenbergresearch/LRTRack#44]
I could not figure out what range to use for the drive cv on the vampyr filter  even an extremely small amount of voltage was too much.
I think it's way too sensitive..
Love the sound

Greetings Peter.

**Comment by lindenbergresearch** [comment]
Thanks for reporting Peter... will check that soon

**Comment by lindenbergresearch** [comment]
It is ok so far, other users seem to be ok with it :) Use attenuverter ;)

**Comment by Petervos2018** [comment]
So to be one the same side 
we both mean the same thing, I mean that the cv range to modulate the drive knob is much to small I think the whole range needs about 1v.
When the drive is in the middle position and I just want to slightly modulate left and right a bit I need about 0.0001V otherwise I go into the "red" on both sides.
And to do that I should use an attenuverter to make the range about +-0.002V from F.I. an LFO.

![DriveRange](https://user-images.githubusercontent.com/46076474/60427846-dab47e00-9bf7-11e9-9e78-c612d27456da.jpg)

You know we can use ranges from +-10V in VCV.
OK I'm exaggerating but what I mean is its a very small range.

Waiting for your release of V1 (It looks gorgeous).

Greetings Peter.
