### ISSUE TITLE
Problem with v0.6.5

### ISSUE THREAD

**Issue by ShofB** [lindenbergresearch/LRTRack#46]
I am running W10 Rack version.6.2c on 2 different machines and this only happens on my primary machine.
I have reinstalled Rack and the lindenberg mods to no avail.
The directory is there and looks fine.
Woldemar loads fine.
The blank wood loads fine.
West coast loads but only 1 skin works on the Westcoast and that is the classic dark. The others just show the knobs and jacks and no writing
Hoe this helps.

**Comment by ShofB** [comment]
I have no idea why but it is working now.  Sorry for the apparently false alarm.

**Comment by lindenbergresearch** [comment]
Allright, I am glad that it finally works for you. Sometimes there are strange behaviours with that open gl drivers...
