### ISSUE TITLE
plugin breaks slug rules

### ISSUE THREAD

**Issue by tank-trax** [lindenbergresearch/LRTRack#49]
built on Debian 9.9

same issue as https://github.com/VCVRack/Rack/issues/1305
plugin builds but when added to Rackv1.dev.4b3508b will crash with the following error:

```
Rack: src/plugin/Plugin.cpp:17: void rack::plugin::Plugin::addModel(rack::plugin::Model*): Assertion `isSlugValid(model->slug)' failed.
Aborted
```

**Comment by lindenbergresearch** [comment]
Should be working now, could you please check? Thanks for reporting! :-)

**Comment by tank-trax** [comment]
yes. this has been building since June 8th. yw and ty2. :-)

**Comment by lindenbergresearch** [comment]
;)
