### ISSUE TITLE
Neo CV Inputs Not Responding to Poly Channels

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [lindenbergresearch/LRTRack#56]
Neo is almost there with Polyphony. It seems to only respond to monophonic CV signals though. Using polyphonic Vult modules for Oscillators and Envelopes because they seem to handle poly correctly. 

Here’s what I’m doing:

1. MIDI CV (Poly Mode - 8 voices, Rotate mode) V/OCT into Bleak
2. Bleak’s output into Neo
3. Neo’s output into Slap’s VCA In
4. MIDI CV Gate into Slap’s Gate In
5. Neo output into mixer
6. Slap’s output controlling Neo’s Frequency CV Input

Result: only the first of 8 voices will trigger the envelope on the filter Frequency.

Expected Result: Filter Frequency Envelope CV should be engaged with each voice.

*Also, would be nice if the module was tagged as polyphonic (don't think the tag needs a separate issue but would be happy to open one).

**Comment by FunkybotsEvilTwin** [comment]
Note: I don't think you need multiple CV visuals to show the polyphony. For instance, 16 arrows/indicators on each knob. I think having the visual reflect the "highest" CV value is good enough. This is how quite a few polyphonic VST synths I own with similar indicators work.

**Comment by lindenbergresearch** [comment]
Neo is now full poly in the upcoming v1.3.0. I also took your suggestion and the CV indicator shows the highest value, thanks for that idea! :)
