### ISSUE TITLE
Missing inner pointers on knobs when cv is added/connected and not moving pointers.

### ISSUE THREAD

**Issue by Petervos2018** [lindenbergresearch/LRTRack#58]
Hi Patrick

Thanks for the 1.3.0 update, can they look more gorgeous... I think not.
However Sangster's inner pointers don't move when cv is added and the attenuverters opened.
And WestCoast does not get any inner pointers when cv is connected.
And none of your modules are in the "Polyphonic" section in the module browser, maybe something wrong in the json file ?

Greetings Peter.

EDIT : the inner pointers on Sangster move when you connect cv to the time, but then all the connected cv pointers move with the same speed/range as the time cv.
Do you understand what I'm trying to say, does this make sense to you ?

**Comment by lindenbergresearch** [comment]
Hi Peter,

thanks much for the bug report! I don't know how I could miss this... retested all bugs here. The polyphonic keyword doesn't work because I used the term 'polyphon' in the json :-( 
Will fix it next week ;) 

Cheers and have a nice Sunday! 
Patrick

**Comment by lindenbergresearch** [comment]
The problem on Sangster is fixed; it used all just the data from CV1 (Time CV) for all CV indicator... ;) Polyphonic has been corrected. Just fixing Westcoast and then you'll get a fixed version.

**Comment by lindenbergresearch** [comment]
Well, Westcoast have a Not Connected mode - if you do not have plugged in any cable it does nothing - this was meant to save resources, but it's not 100% correct. I removed it. Just try: If you connect any input, you'll see CV indicators running as well ;)

**Comment by Petervos2018** [comment]
>if you do not have plugged in any cable it does nothing - this was meant to save resources, but it's not 100% correct.

I just tried and you are right :+1: 
but when I remove the cv cables the pointers stay like this :
![WestCoastBug-19122019](https://user-images.githubusercontent.com/46076474/71194470-3ea52e80-228c-11ea-9585-2a38539c08d0.png)

But I guess you already know this and that is why you removed it.
Waiting for the fixed version,
Thanks Peter.

**Comment by lindenbergresearch** [comment]
Yes I know, it's buggy... :) Thanks again for reporting. All issues have been fixed. Cheers
