### ISSUE TITLE
0.5.0 builds

### ISSUE THREAD

**Issue by phdsg** [lindenbergresearch/LRTRack#7]
last commit, except:
commented out the VCO in lindenbergresearch.cpp and fixed the shaper to build in linux

[LindenbergResearch-0.5.0-lin.zip](https://github.com/lindenbergresearch/LRTRack/files/1494649/LindenbergResearch-0.5.0-lin.zip)
[LindenbergResearch-0.5.0-mac.zip](https://github.com/lindenbergresearch/LRTRack/files/1494650/LindenbergResearch-0.5.0-mac.zip)
[LindenbergResearch-0.5.0-win.zip](https://github.com/lindenbergresearch/LRTRack/files/1494655/LindenbergResearch-0.5.0-win.zip)

**Comment by lindenbergresearch** [comment]
Thanks a lot, it actually was my task for today morning ;)

**Comment by lindenbergresearch** [comment]
@phdsg If you like, it would be very nice if you can compile a windows and linux version on my releases, I currently have no time to setup VMs to do so ;) cheers

**Comment by phdsg** [comment]
can do and will. but later today.

**Comment by lindenbergresearch** [comment]
Not today, I mean for the next release. Maybe at the weekend ;) Thanks!

**Comment by Atavic** [comment]
:+1: Thanks to both of you!
