### ISSUE TITLE
Failed to load library ./plugins/LRTRack/plugin.so

### ISSUE THREAD

**Issue by Cordoha** [lindenbergresearch/LRTRack#8]
Ubuntu 16.04
Rack 0.5.0 dev

[warning] Failed to load library ./plugins/LRTRack/plugin.so: ./plugins/LRTRack/plugin.so: undefined symbol: _Z17getPhaseIncrementf

**Comment by Cordoha** [comment]
#7 Linux build works. Compiling does not. So the issue may have been fixed before the build.

**Comment by lindenbergresearch** [comment]
Check the current sources, I excluded the VCO until it is finished. Always use the released builds :) or use to checkout TAGs with the release version, if you want to build it on your own. Release versions should have been tested ;)
